# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.

[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.1.0"

[[constraint]]
  name = "github.com/newrelic/go-agent"
  version = "2.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/tylerb/gls"

[[constraint]]
  name = "gopkg.in/redis.v5"
  version = "5.2.9"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.5.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.4.0"

[prune]
  go-tests = true
  unused-packages = true

# fix a bug related to the fsnotify package
[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[[constraint]]
  name = "github.com/bluele/go-timecop"
  branch = "master"